// <auto-generated />
using System;
using GestionNotificaciones.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GestionNotificaciones.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241210123640_AddNotificaciones")]
    partial class AddNotificaciones
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GestionNotificaciones.Models.EstadoReporte", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("EstadosReporte");
                });

            modelBuilder.Entity("GestionNotificaciones.Models.Notificacion", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("idReporte")
                        .HasColumnType("integer");

                    b.Property<bool>("leido")
                        .HasColumnType("boolean");

                    b.Property<string>("mensaje")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("idReporte");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("GestionNotificaciones.Models.Reporte", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("idEstado")
                        .HasColumnType("integer");

                    b.Property<int>("idTipo")
                        .HasColumnType("integer");

                    b.Property<int>("idVecino")
                        .HasColumnType("integer");

                    b.Property<int>("imagen")
                        .HasColumnType("integer");

                    b.Property<string>("ubicacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("idEstado");

                    b.HasIndex("idTipo");

                    b.HasIndex("idVecino");

                    b.ToTable("Reportes");
                });

            modelBuilder.Entity("GestionNotificaciones.Models.TipoReporte", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("TiposReporte");
                });

            modelBuilder.Entity("GestionNotificaciones.Models.Usuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("contraseña")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<char>("dv")
                        .HasColumnType("character(1)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("rut")
                        .HasColumnType("integer");

                    b.Property<int>("telefono")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("GestionNotificaciones.Models.Vecino", b =>
                {
                    b.Property<int>("id")
                        .HasColumnType("integer");

                    b.Property<string>("direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Vecinos");
                });

            modelBuilder.Entity("GestionNotificaciones.Models.Notificacion", b =>
                {
                    b.HasOne("GestionNotificaciones.Models.Reporte", "Reporte")
                        .WithMany()
                        .HasForeignKey("idReporte")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reporte");
                });

            modelBuilder.Entity("GestionNotificaciones.Models.Reporte", b =>
                {
                    b.HasOne("GestionNotificaciones.Models.EstadoReporte", "Estado")
                        .WithMany()
                        .HasForeignKey("idEstado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionNotificaciones.Models.TipoReporte", "Tipo")
                        .WithMany()
                        .HasForeignKey("idTipo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionNotificaciones.Models.Vecino", "Vecino")
                        .WithMany()
                        .HasForeignKey("idVecino")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");

                    b.Navigation("Tipo");

                    b.Navigation("Vecino");
                });

            modelBuilder.Entity("GestionNotificaciones.Models.Vecino", b =>
                {
                    b.HasOne("GestionNotificaciones.Models.Usuario", "Usuario")
                        .WithOne()
                        .HasForeignKey("GestionNotificaciones.Models.Vecino", "id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
